[build]
  command = "echo 'Building Open Frame...' && mkdir -p dist && cp frame.json dist/frame.json"
  publish = "dist"

[context.production]
  target = "production"

[context.deploy-preview]
  target = "deploy-preview"